### ISSUE TITLE
Cannot get projects loading

### ISSUE THREAD

**Issue by lukebarone** [digitalcraftsman/hugo-freelancer-theme#17]
Hi there,

Excuse me for this being my first go at Hugo, so I may have just done something wrong.

I want to load up projects on my page. I have tried copying just one of the files from the `exampleSite/data/projects/` folder to my `/data` folder, ran Hugo, and no projects. I also tried copying it to `/projects`, and `/data/projects`, but none of them are rendering items under the Projects section of the page.

Any hints? Below is what I have right now:

```yaml
modalID: 1
title: Server Virtualization
date: 2014-07-01
img: cabin.png
client: You!
clientLink: "#"
category: Servers
description: Saving on electricity, network ports, and hardware costs, Virtualizing servers in your organization can help increase availability of your services, and isolate containers to expand as required.
```
